version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database
      - summarization

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

  summarization:
    build:
      context: ./summarization
      dockerfile: Dockerfile.summarization
    ports:
      - "8000:8000"
    volumes:
      - ./summarization:/app

  database:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: