version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1  # Enable MPS fallback for unsupported operations
    ports:
      - "5200:5002"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5300:5003"
