version: '3.8'

services:
  backend:
    build:
      context: ./backend
    runtime: nvidia  # Use NVIDIA runtime for GPU
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Access all available GPUs
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "5200:5002"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5300:5003"
